
# MySQL
spring.datasource:
  url: jdbc:mysql://localhost:3306/duster
  username: duster
  password: dusterPassword
spring.jpa:
  database-platform: org.hibernate.dialect.MariaDB10Dialect
  hibernate.ddl-auto: update

# Server port
server.port: 8080

# Logging setup
logging:
  file:
    name: dusterapp.log
  level:
    org.springframework: INFO
    com.essteyr.mammothmanager: DEBUG

connectivity:
  server-url: "https://smog-w-toruniu.pl/api/v1/submit"
  server-token: "fawefraw3"

# Web modules
modules:
  pm: true
  temperature: true

# Sampler
sampler:
  period: 120
  pigpio:
    url: "http://localhost"
  sensors:
    pm:
      - name: "hm3301Dummy"
        pigpio:
          sda: 2
          scl: 3
          i2c: 0x40
