
# MySQL
spring.datasource:
  url: jdbc:mysql://localhost:3306/duster
  username: duster
  password: dusterPassword
spring.jpa:
  database-platform: org.hibernate.dialect.MariaDB10Dialect
  hibernate.ddl-auto: update

# Server port
server.port: 8080

# Logging setup
logging:
  file:
    name: duster.log
  level:
    org.springframework: INFO
    com.essteyr.mammothmanager: DEBUG

connectivity:
  server-url: "http://localhost:8081/api/v1/record"
  server-token: "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoibmFtZSIsInJvbGUiOiJST0xFX1NFTlNPUiIsImV4cCI6MTYwOTkzODM3NH0.cFAee5ANAStqDtM9b9itk7G4UOra3f88_C5oy9Rv670"

# Web modules
modules:
  pm: true
  temperature: true

# Sampler
sampler:
  period: 120
  pigpio:
    url: "http://localhost"
  sensors:
    pm:
      - name: "hm3301Dummy"
        pigpio:
          sda: 2
          scl: 3
          i2c: 0x40
