#!/bin/bash

if [ $# == 1 ]
then
    # Get config file path
    CONFIG_PATH=`pwd`/$1

    # Go to the directory of this script
    cd `dirname $0`

    # Launch dusterapp
    java -jar *.jar --spring.config.location="$CONFIG_PATH" &
    WEBAPP=$!

    # Launch sampler
    cd sampler;
    python3 sampler.py $CONFIG_PATH &
    SAMPLER=$!

    # Wait for any of the proceses to end/fail
    wait -n $SAMPLER $WEBAPP

    # Kill both processes
    kill -9 $SAMPLER && kill -9 $WEBAPP
else
    echo "Usage: ./duster path_to_config.yml"
fi
