# JDBC data
#spring.datasource.url: jdbc:sqlite:../db/concentration.sqlite

# MySQL
spring.datasource:
  url: jdbc:mysql://localhost:3306/duster
  username: duster
  password: dusterPassword
spring.jpa:
  database-platform: org.hibernate.dialect.MariaDB10Dialect
  hibernate.ddl-auto: update

# Server port
server.port: 8080

# Logging setup
logging:
  file:
    name: dusterapp.log
  level:
    org.springframework: INFO
    com.essteyr.mammothmanager: DEBUG

# Resubmit data to
connectivity:
  server-url: "https://smog-w-toruniu.pl/api/v1/record"
  server-token: "werwearewa"


# Web modules:
modules:
  pm: true
  temperature: true

